/*
 * Copyright (c) 2024-2025 XDay
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files (the
 * "Software"), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
 * CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */


/*
    This file is auto generated by tool. if modify manually, you need remove [SLGSerializationClassAttribute] from class definition in case of being overridden!!!
*/

using XDay;


internal partial class Test
{
    public void Save(ISerializer writer, string label, IObjectIDConverter converter)
    {
        writer.WriteInt32(m_Version, "Test.Version");




        writer.WriteInt32(m_IntField, "Int Field");


        writer.WriteInt32List(m_IntListFields, "Int Fields");


        writer.WriteList(m_TestObjectListFields, "Test Object List Fields", (obj, index) =>
        {
            writer.WriteStructure($"m_TestObjectListFields {index}", () =>
            {
                obj.Save(writer, "", converter);
            });
        });


        writer.WriteInt32Array(intArray, "Test int Array Fields");


        writer.WriteStructure("Test Object2", () =>
        {
            m_Obj2.Save(writer, "", converter);
        });


    }
}

